"""Email notification for high-relevance job alerts."""
from __future__ import annotations

import logging
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

logger = logging.getLogger(__name__)


def _build_html_email(jobs: list[dict]) -> str:
    """Build an HTML email body for the job digest."""
    rows = ""
    for job in jobs:
        score = job.get("relevance_score", 0)
        score_color = "#3fb950" if score >= 70 else "#d29922" if score >= 40 else "#f85149"
        rows += f"""
        <tr>
          <td style="padding:8px 12px;border-bottom:1px solid #30363d;">
            <a href="{job.get('link', '#')}" style="color:#58a6ff;text-decoration:none;font-weight:500;">{job.get('title', 'N/A')}</a>
          </td>
          <td style="padding:8px 12px;border-bottom:1px solid #30363d;color:#d2a8ff;">{job.get('company', 'N/A')}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #30363d;color:{score_color};font-weight:700;">{score}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #30363d;color:#8b949e;font-size:0.85rem;">{job.get('llm_reason', '')}</td>
          <td style="padding:8px 12px;border-bottom:1px solid #30363d;">
            <a href="{job.get('link', '#')}" style="color:#f0883e;text-decoration:none;">Apply</a>
          </td>
        </tr>"""

    return f"""
    <html>
    <body style="background:#0d1117;color:#c9d1d9;font-family:sans-serif;padding:20px;">
      <h2 style="color:#58a6ff;">DevOps Job Alert — {len(jobs)} New Matching Position{'' if len(jobs)==1 else 's'}</h2>
      <table style="width:100%;border-collapse:collapse;background:#161b22;border-radius:8px;overflow:hidden;">
        <thead>
          <tr style="background:#21262d;">
            <th style="padding:10px 12px;text-align:left;color:#8b949e;font-size:0.8rem;">Title</th>
            <th style="padding:10px 12px;text-align:left;color:#8b949e;font-size:0.8rem;">Company</th>
            <th style="padding:10px 12px;text-align:left;color:#8b949e;font-size:0.8rem;">Score</th>
            <th style="padding:10px 12px;text-align:left;color:#8b949e;font-size:0.8rem;">Reason</th>
            <th style="padding:10px 12px;text-align:left;color:#8b949e;font-size:0.8rem;">Link</th>
          </tr>
        </thead>
        <tbody>{rows}</tbody>
      </table>
      <p style="color:#484f58;font-size:0.8rem;margin-top:16px;">
        Generated by DevOps Job Agent &mdash; update your preferences in config.yaml
      </p>
    </body>
    </html>"""


def _build_text_email(jobs: list[dict]) -> str:
    """Build a plain-text fallback for the job digest."""
    lines = [f"DevOps Job Alert — {len(jobs)} New Matching Position{'s' if len(jobs)!=1 else ''}\n"]
    for job in jobs:
        lines.append(f"  [{job.get('relevance_score', 0)}] {job.get('title', 'N/A')} at {job.get('company', 'N/A')}")
        lines.append(f"       {job.get('llm_reason', '')}")
        lines.append(f"       Apply: {job.get('link', '')}")
        lines.append("")
    return "\n".join(lines)


def send_digest(
    jobs: list[dict],
    smtp_host: str,
    smtp_port: int,
    smtp_user: str,
    smtp_pass: str,
    smtp_from: str,
    alert_email_to: str,
) -> bool:
    """Send a single digest email for qualifying jobs. Returns True on success."""
    if not jobs:
        logger.info("No jobs to notify about — skipping email")
        return True

    try:
        msg = MIMEMultipart("alternative")
        msg["Subject"] = f"DevOps Job Alert — {len(jobs)} New Position{'s' if len(jobs)!=1 else ''}"
        msg["From"] = smtp_from
        msg["To"] = alert_email_to

        msg.attach(MIMEText(_build_text_email(jobs), "plain"))
        msg.attach(MIMEText(_build_html_email(jobs), "html"))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_pass)
            server.sendmail(smtp_from, [alert_email_to], msg.as_string())

        logger.info("Sent digest email with %d jobs to %s", len(jobs), alert_email_to)
        return True

    except smtplib.SMTPException as e:
        logger.error("SMTP error sending digest: %s", e)
        return False
    except Exception as e:
        logger.error("Unexpected error sending digest email: %s", e)
        return False
